services:
  server:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: werminal_server
    restart: always
    expose:
      - "8080"
    networks:
      main_network:

  nginx:
    build:
      context: ..
      dockerfile: ./nginx/Dockerfile
    container_name: werminal_nginx
    restart: always
    ports:
      - "127.0.0.1:8803:80"
    networks:
      main_network:
    depends_on:
      - server

networks:
  main_network:
    driver: bridge

